### ISSUE TITLE
problem in summarizing tests

### ISSUE THREAD

**Issue by xilingsabatelli** [SheaML/ExDFOIL#1]
Hi! I got a problem when running the summarizer_alt.sh, I prepared all the data file produced according to the protocol (folder: /counts, /dfoil ), and the .sh script from package, and it gives multiple repeat error message:

basename: extra operand ‘AAAAA’
Try 'basename --help' for more information.
tail: cannot open ‘#chrom\tposition\tAAAAA\tAAABA\tAABAA\tAABBA\tABAAA\tABABA\tABBAA\tABBBA\tBAAAA\tBAABA\tBABAA\tBABBA\tBBAAA\tBBABA\tBBBAA\tBBBBA’ for reading: No such file or directory
cat: dfoil/.dfoil_alt: No such file or directory
cat: dfoil/.dfoil_alt: No such file or directory

The working directory is  rooted and should be correct (/home/XXX/Documents/xiling/exdfoil).
Could you please give me some suggestion on how to solve this problem?

**Comment by xilingsabatelli** [comment]
I solve the problem by using the pipeline in Quick Start: 
parallel 'summarizer_alt.sh < <(echo {})' ::: counts/*.counts
and it workes.
The pipeline in the Tutorial:
parallel './summarizer_alt.sh < $(echo {})' ::: counts/*.counts
not work for me.

**Comment by slambert-git** [comment]
Thanks -- that line is now fixed in the Tutorial code

**Comment by xilingsabatelli** [comment]
Hi!
I am also doing the four taxon analysis (Dstat) with this program, i'm not really good at programming, so could you please give me some suggestion on changing the script to fit the Dstat analysis? Especially for the DFOIL_Picker.R:

#get all clades of size 2 with MRCA at each node
get_pairs<-function(node){
  desc1=alldescs[[which(nodes[,2] == node)]] 
  child1=desc1[1]
  child2=desc1[2]
  if(child1 <= tiplen){
    cd1=tree$tip.label[child1]
  } else {
    cdtemp=alldescs[[which(nodes[,2] == child1)]]
    cdtemp=cdtemp[cdtemp <= tiplen]
    cd1=tree$tip.label[cdtemp]
  }
  if(child2 <= tiplen){
    cd2=tree$tip.label[child2]
  } else {
    cdtemp=alldescs[[which(nodes[,2] == child2)]] 
    cdtemp=cdtemp[cdtemp <= tiplen]
    cd2=tree$tip.label[cdtemp]
  }
  result=expand.grid(cd1,cd2)
  return(apply(result,1,paste,collapse=" "))
}

allpairs=lapply(nodes[,2],get_pairs)


#prepare results vector
results=vector()

#get all valid combinations for each node
for(i in nodes[,2]){
  h1=nodes[nodes[,2] == i ,1]
  desc1=alldescs[[which(nodes[,2] == i)]] 
  compnodes=nodes[!(nodes[,2] %in% c(i,desc1)) & nodes[,1] >= h1,2]
  if(length(compnodes) == 0){
    next
  } else{
    compairs=unlist(lapply(compnodes,function(x) allpairs[[which(nodes[,2] == x)]]))
    nextres=apply(expand.grid(compairs,allpairs[[which(nodes[,2] == i)]]),1,paste,collapse=" ")
    results=c(results,nextres)
  }
}

It would be really useful to use it to select out the proper taxon, looking forward to your replying!
